### ISSUE TITLE
I would like to create a HTTP request

### ISSUE THREAD

**Issue by sabarishsubramanian** [arjunmahishi/loadbalancer-in-go#1]
Hello 

thank you for your guidelines for the load balancer.

In here I would like to pass HTTP request with data in it with some periodicity and check the load balancer.

could you please help me out and let me know how can it be done.

Thank you

**Comment by arjunmahishi** [comment]
There is a code snippet in the README to bombard HTTP requests to this load-balancer:
```bash
for i in {1..20}; do curl 127.0.0.1:8000; done
```
This will make 20 requests to the load balancer. If you want to control the periodicity, you can add a `sleep`:
```bash
# will sleep for 2 sec between requests
for i in {1..20}; do curl 127.0.0.1:8000; sleep 2; done
```
If you want to add a data to this request, use the `--data` flag in curl

**Comment by sabarishsubramanian** [comment]
Hey arjun 

Thank you for your feedback.

My query is I wanted to create some HTTP requests as part of client side. This request should go to my load balancer and then the load balancer distributes in round robin fashion.

So I wanted to create some suppose 10 load as client how do I create it I mean different types of HTTP request with load.

i saw few codes such as GET PUT DELETE some kind is that the way to use or some thing else.

**Comment by arjunmahishi** [comment]
I don't think understand the question. You want to make HTTP requests to the loadbalancer to check if it is routing properly right? Thats exactly what the curl command will do.

```bash
for i in {1..20}; do curl 127.0.0.1:8000; sleep 2; done
```

(also, if there are further questions, can we move this to the [discussion tab](https://github.com/arjunmahishi/loadbalancer-in-go/discussions)? Thanks)
